### PR TITLE
Added tooltip

### PR DESCRIPTION
**Pull request by erin-xu**
### Summary 
Added tooltip with queue position.

### Test Plan 
- Hover over queue position and check that tooltip with correct position is displayed.

### Breaking Changes 

None

- [ ] I have updated the documentation accordingly.
- [ ] My PR adds a @ts-ignore

### CODE REVIEW

**Review by triple-jay — CHANGES_REQUESTED** [review]
Thanks for working on this Erin! I did verify to see that the tooltip is shown when hovering over queue position :). If it isn't too much work, could you disable this on the TA side? Currently, they can see the tooltip when hovering over each queue position of students, and I don't think they need to see this on their end.

Screen Shot 2022-03-03 at 11 06 20 AM

**Review by danakim21 — CHANGES_REQUESTED** [review]
Great work done Erin!! I also agree with Jeremy's point that the professors or TAs don't need to see the tooltip. Also, it would be better if the tooltip is closer to the question because it seems like there's a lot of space in between right now.

**Review by triple-jay — APPROVED** [review]
Looks great Erin! I can no longer see the position on the TA side anymore :)

**Review by danakim21 — APPROVED** [review]
Thanks for making the changes Erin!! I've checked that the tooltip is visible only to the students and the spacing is better 👍

**Pull request merged**
