### PR TITLE
Testing + small css fixes

### PR DESCRIPTION
**Pull request by NIDHI2023**
### Summary 

- fixed bug with how wrappedData was stored from collection, it should now show correct numbers
- changed "semester" words to "year" in ui
- added white hover to dots to make it easier to see you can click
- fixed hover on arrows to resemble the close icon

### Notes 

- If we're considering mobile users, anything below 800 px you can't easily exit Wrapped or click to other slides

800px:
image

700px:
image

### Breaking Changes 

None

- [ ] I have updated the documentation accordingly.
- [ ] My PR adds a @ts-ignore

### CODE REVIEW

**Review by rgu0114 — APPROVED** [review]
Good note abt the mobile users, we'll need to patch that up in a future pr

**Review by rgu0114 — CHANGES_REQUESTED** [review]
oh remember to pull from `wrapped` and not `wrapped-fa24`

**Review by swang235 — APPROVED** [review]
i agree w richard about wrapped-fa24 but otherwise lgtm! good catch on mobile view and nice work nidhi!

**Comment by NIDHI2023** [comment]
i haven't tested this on prod database (since it wasn't working for me) so I think this should be tested on prod before merging

**Review by rgu0114 — APPROVED** [review]
lgtm!

**Pull request merged**
