### PR TITLE
Fix arrow-down incorrect rotation css

### LINKED ISSUE #294: Rotated dropdown arrow on session info header on Firefox
Should be rotated downwards.

image

### LINKED ISSUE #296: Location input looks incorrect on Microsoft Edge
The location input for creating a question appears with a scrollbar by default when there is no entered text in Microsoft Edge. It works correctly when some text is entered.

Found by Helen Yang, Laura Sizemore

### PR DESCRIPTION
**Pull request by SamChou19815**
### Summary 

Fix #294.

### Test Plan 

Chrome:
Screen Shot 2020-04-09 at 00 31 37
Firefox:
Screen Shot 2020-04-09 at 00 32 04
Safari:
Screen Shot 2020-04-09 at 00 32 38

### CODE REVIEW

**Comment by SamChou19815** [comment]
> Array doesn't rotate at all on web and mobile. Is that correct behaviour?

What's your os and browser on mobile?
Screenshot?

**Comment by SamChou19815** [comment]
@abcdefguan

**Comment by abcdefguan** [comment]
Yes yes I've seen it. Give me a bit.

**Comment by abcdefguan** [comment]
Oh so I think it's probably fine.
What I meant to ask was whether the arrow should stay in that rotation in all states.
Unexpanded
Screenshot from 2020-04-10 01-21-31
Expanded
Screenshot from 2020-04-10 01-21-38

Should the arrow always be like ∨ all the time whether expanded or unexpanded?
Or should it be like ∨ when not expanded and ∧ when expanded?
Was that why there was that additional rotate 90 degrees code?

**Comment by SamChou19815** [comment]
> Oh so I think it's probably fine.
> 
> What I meant to ask was whether the arrow should stay in that rotation in all states.
> 
> Unexpanded
> 
> Screenshot from 2020-04-10 01-21-31
> 
> Expanded
> 
> Screenshot from 2020-04-10 01-21-38
> 
> 
> 
> Should the arrow always be like ∨ all the time whether expanded or unexpanded?
> 
> Or should it be like ∨ when not expanded and ∧ when expanded?
> 
> Was that why there was that additional rotate 90 degrees code?

I don't know. It's probably up for design to figure out. The addition rotate code I deleted is simply wrong: it's not a valid css property.

**Pull request merged**
