### PR TITLE
Major Queue Me In Update

### PR DESCRIPTION
**Pull request by ngwattcos**
### Summary 

This is a major update to Queue Me In that brings new features, quality of life changes, and bug fixes. Here is an abbreviated list of updates:

## New Features
- Students and TAs can write comments to each other on the student question
- TA performance tracking/average wait time estimate

## Important Quality-Of-Life Changes
- Lots of new/re-enabled notifications (for when your question is up, when you receive a comment from a student or TA)
- Warnings to enable both browser and system-wide notifications
- Student netIDs are shown on the question box to the TA in case they need to reach out directly
- improvements to discrepancies in the size of the components in the list of office hours (professor-side)
- improvements to the Login page

## Bug Fixes
- Professors will not accidentally downgrade TAs or themselves when selecting the role drop-down and cancelling midway.
- Inactive assignments will have selectable secondary tags that enable students to (fix the inconsistency in the tags)
- Queue position number is now correctly calculated; there is no longer a discrepancy between queue position number and the number of student ahead

## Thanks
Thanks to @abcdefguan for enabling Firebase cloud functions. This is a huge step forward because it enables important features like more efficient TA onboarding, chronjobs to clear out old questions and statistics, and much more...
...to @nada-attia for implementing the notifications banner and modal prompting users to enable desktop notifications...
...to @vladiatrinh for improving our login page, the very first thing users will see when they use Queue Me In
...to @triple-jay (Jeremy) for implementing and fixing up desktop notifications for comments and fixing course selection on the homepage
... to @abcdefguan for adding support for TA and student comments to each other
...to @ewlsh for creating support for different types (virtual, hybrid, and in-person) of office hours and better integrating zoom links
...to @vladiatrinh for displaying student netIDs on the question to the TA in case they need to reach out
...to @nada-attia for fixing the age-old discrepancies in calculating queue position
...to @ewlsh for the important first steps in making Queue Me In more accessible and navigable
...to the designers for paving the way forward for Queue Me In

### Notes 

This implements Firebase Cloud Functions and automatically deploys using the CI/CD (thanks @abcdefguan). Cloud functions will be used in several important incoming features.

### Breaking Changes 

None

- [ ] I have updated the documentation accordingly.
- [ ] My PR adds a @ts-ignore

### CODE REVIEW

**Review by triple-jay — APPROVED** [review]
All the features look good :)! Cloud functions are still slightly buggy, but they do not break the application so I don't think it's that big of a deal. Style looks great as well!

**Comment by abcdefguan** [comment]
@triple-jay Could you report what specific bugs you encountered with cloud functions? Some older office hours (before I actually deployed these cloud functions) would have some bad state. However, if you create a new office hour it should work correctly.

**Comment by ngwattcos** [comment]
@abcdefguan This PR isn't ready until we can confirm that CI/CD is set up correctly (i.e., it deploys to the production version of Queue Me In instead of staging). Can you confirm this?

**Comment by abcdefguan** [comment]
Oh this PR should be ready. I didn't change any CI/CD settings. The other time wrong, the deploy just straight up failed because it was missing some dependencies.

**Review by abcdefguan — APPROVED** [review]
Should be ok. I've reviewed some of the individual PRs going into this and they were ok

**Comment by ngwattcos** [comment]
@abcdefguan Will the cloud function deployment point to prod?

**Comment by abcdefguan** [comment]
It should. This is a project setting. When you firebase deploy it deploys everything at once to the target, including hosting and cloud functions. I mean you really gotta test it out, but I think it should deploy cloud functions to prod

**Pull request merged**
