### PR TITLE
New upload roles design

### PR DESCRIPTION
**Pull request by erin-xu**
### Summary 

This PR implements a new design to upload roles. On the Manage Roles page of the Dashboard, the new "Import Professors/TAs" button opens a modal, where the user can choose to upload roles manually or upload a file. The CSV upload option allows professors to select or drag/drop a .xlsx or .csv file with roles to upload. The selected file should only be shown if it is in the correct format. If not, an error is displayed and the selected file is not shown. To upload manually, emails and roles can be entered into a table. Roles can be uploaded once a valid email is entered for every row and at least one email and role is entered. Once roles are uploaded correctly, the modal closes, and a confirmation message is shown. 

### Test Plan 

CSV Upload
- Check that files can be uploaded by using both select and drag/drop options.
- Check that an error is displayed and the uploaded file is not shown if the file is not in .xlsx or .csv format.
- Check that an error is displayed and the uploaded file is not shown if the file contains roles other than the allowed roles (TA, Professor).
- If the uploaded file has the correct format, the file name should be shown in the box.
- After a valid file is uploaded and the confirm button is clicked, the modal should close and a message should show pending roles.
- The CSV upload modal should reset once the modal is closed. Check that when the modal is exited and reopened, no file or error messages are shown. 

Manual Upload
- Check that the delete icons delete the corresponding row in the table.
- Check that rows can be added using the add icon. 
- Check that if several rows are added, all rows can be viewed by scrolling vertically. 
- Check that an error is displayed and the confirm button does not work if there is an invalid email or empty email cell. 
- Check that an error is displayed and the confirm button does not work if there are no rows in the table.
- After roles are entered in the correct format and the confirm button is clicked, the modal should close and a message should show pending roles.
- The manual upload modal should reset once the modal is closed. Check that when the modal is exited and reopened, the default three rows are shown. 
### Breaking Changes 

None

- [ ] I have updated the documentation accordingly.
- [ ] My PR adds a @ts-ignore

### CODE REVIEW

**Review by triple-jay — CHANGES_REQUESTED** [review]
Thanks for working on this Erin! The csv upload worked as expected, but the manual add didn't work on my end—once you fix that it should be good to go!

**Review by danakim21 — CHANGES_REQUESTED** [review]
I checked that both using select and drag/drop works, and errors are displayed if the given file has a wrong file type or invalid roles are included. I don’t think adding manually works right now, but everything else looks great!

**Review by triple-jay — CHANGES_REQUESTED** [review]
Thanks for working so hard on this Erin! I did test that the manual entry now works, so great job on that! You really worked hard this semester to grow, and it really shows in your PRs :).

Very small changes, but can you make it so that the cursor becomes a pointer when hovering over the trash can, as well as center the trash can vertically so that it aligns perfectly with each row? Also, the image does seem a little blurry compared to the Figma—try exporting at 4x with the png option instead of the svg and see if that helps.

Other than that, it should be good to go! Once again, thanks for working on this!

**Review by triple-jay — APPROVED** [review]
Looks great Erin! Feel free to merge it in now :)

**Review by triple-jay — CHANGES_REQUESTED** [review]
Everything looks good Erin! I just need you to revert the two lines in firebase.ts before merging, but I'll approve as soon as you do that!

**Review by triple-jay — APPROVED** [review]
Perfect thanks!

**Review by danakim21 — APPROVED** [review]
Everything works correctly when I followed your test plan. Great work!

**Pull request merged**
