### PR TITLE
change edit courses frontend

### PR DESCRIPTION
**Pull request by swang235**
### Summary 
Changing the frontend of the edit classes page. Updating styling to be more aligned with the rest of the website.

_previous design:_
image

_new design:_
image

### Test Plan
- run yarn start and confirm that search bar functions properly.

### Breaking Changes 

None

- [ ] I have updated the documentation accordingly.
- [ ] My PR adds a @ts-ignore

### CODE REVIEW

**Review by rgu0114 — COMMENTED** [review]
Great work with this so far Sophie, I like the documentation you included and how you maintained the styling in accordance with the rest of QMI. I think one thing that would be helpful, though, is if you included a couple screenshots of your changes so it's easier to see which frontend updates you made

**Comment by burninglilies** [comment]
Looks great so far! Just remember to check for lint errors. Your only error rn is an indentation one so should be a v small fix

**Review by rgu0114 — CHANGES_REQUESTED** [review]
The code looks good to me but when testing on my end, the proportions on some screen sizes seem off. Could you double check that this fits the designs on a range of screen sizes?
Laptop:
Screen Shot 2024-03-14 at 4 00 47 PM
Mobile width messes with things 😕:
Screen Shot 2024-03-14 at 4 02 51 PM

**Review by rgu0114 — CHANGES_REQUESTED** [review]
Thanks for working so hard on these changes! Looking at the edits you made, I think it's looking a lot better. Could you update the most recent dependencies/fix merge conflicts though? Having trouble running locally.

**Pull request closed without merging**
