### PR TITLE
Release w/ master merged

### PR DESCRIPTION
**Pull request by JBoss925**
I'm j merging in master, you feel?

### CODE REVIEW

**Comment by ngwattcos** [comment]
Thank you so much for the fix, Jagger. I just added a small linting fix. We will approve this PR ASAP after a brief testing session tomorrow!

**Review by ngwattcos — APPROVED** [review]
Thank you so much for rebasing release with master! Originally was gonna a couple hours grinding out this with the QMI crew. We have gone through the local clone and tested for regressions - no problems here! Also, the code passes the linter. (I added a small fix in indentation that fixed a linter error).

**Review by triple-jay — APPROVED** [review]
We did this as a group review :). Discussions and the landing page seem to work as they should, and admin seems to work well also. Thanks a lot for helping us!

**Review by rmz38 — APPROVED** [review]
I reviewed with Scott and Jeremy and agree that everything is working fine, thank you Jagger for the huge cleanup!

**Comment by pooja654** [comment]
One thing I noticed was that when you upvote a comment and it moves up, the corresponding tags below it (such as Assignment, Problem 4, etc.) get indented...

**Pull request merged**
